### ISSUE TITLE
Add Negative  Values

### ISSUE THREAD

**Issue by Bercraft** [FairBear/AI_PovX#5]
Can you add negative values for the X Y Z offsets thank you

**Comment by FairBear** [comment]
Yes, just input a positive number first (like `1.0`), then put a negative sign at the left-most side (`-1.0`.) I can't do anything to make it easier because this is on the `ConfigurationManager`'s side, which is not mine.

**Comment by Bercraft** [comment]
Thank you

Il mar 13 ott 2020, 00:08 FairBair <notifications@github.com> ha scritto:
